"""empty message

Revision ID: 200f470113fa
Revises: 
Create Date: 2023-12-04 20:38:03.433612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '200f470113fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('html_validation_log',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('site_id', sa.Integer(), nullable=False),
                    sa.Column('logs', sa.TEXT(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('performance_log',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('site_id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('tasks',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('site_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.VARCHAR(), nullable=False),
                    sa.Column('task', sa.VARCHAR(), nullable=False),
                    sa.Column('timeout', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('performance_log')
    op.drop_table('html_validation_log')
    # ### end Alembic commands ###
